import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local"
import { Open_Sans } from "next/font/google"
const mainFont = Open_Sans({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Blocket - Enhanced car search",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={mainFont.className}>{children}</body>
    </html>
  );
}
