import { z } from "zod"

export const CarSearchResponseObject = z.object({
  carBrand: z.union([z.literal("BMW"), z.null()]),
  carModel: z.union([z.enum([
    "114i",
    "116",
    "118",
    "118i",
    "120",
    "123",
    "125",
    "128ti",
    "130",
    "135",
    "140",
    "2-serien",
    "216",
    "218",
    "220",
    "225",
    "225xe",
    "228",
    "235",
    "240",
    "3-serien",
    "316",
    "318",
    "320",
    "323",
    "325",
    "328",
    "330",
    "330e",
    "335",
    "335i",
    "340",
    "4-serien",
    "418",
    "420",
    "428",
    "430",
    "435",
    "440",
    "5-serien",
    "518",
    "520",
    "523",
    "525",
    "528",
    "530",
    "535",
    "540",
    "545",
    "550",
    "6-serien",
    "620",
    "630",
    "635",
    "640",
    "645",
    "650",
    "7-serien",
    "728",
    "730",
    "735",
    "740",
    "745",
    "750",
    "760",
    "8-serien",
    "840",
    "850",
    "M-modeller",
    "M-serien",
    "M1",
    "M2",
    "M3",
    "M340",
    "M4",
    "M440",
    "M5",
    "M550",
    "M6",
    "M8",
    "M850i",
    "X-serien",
    "X1",
    "X2",
    "X3",
    "X4",
    "X5",
    "X5M",
    "X6",
    "X6M",
    "X7",
    "Z-serien",
    "Z3",
    "Z4",
    "i-serien",
    "i3",
    "i3s",
    "i4",
    "i5",
    "i7",
    "i8",
    "iX",
    "iX1",
    "ix3",
  ]), z.null()]),
  fuelType: z.union([
    z.enum(["Bensin", "Diesel", "El", "Miljöbränsle/Hybrid"]),
    z.null()
  ]),
  chassiType: z.union([
    z.enum(["SUV", "Cab", "Coupé", "Familjbuss", "Halvkombi", "Kombi", "Sedan", "Yrkesfordon"]),
    z.null()
  ]),
  maxPrice: z.union([
    z.number(),
    z.null()
  ]),
  minPrice: z.union([
    z.number(),
    z.null()
  ]),
  minModelYear: z.union([
    z.number(),
    z.null()
  ]),
  maxModelYear: z.union([
    z.number(),
    z.null()
  ]),
  minMileage: z.union([
    z.number(),
    z.null()
  ]),
  maxMileage: z.union([
    z.number(),
    z.null()
  ]),
  transmissionType: z.union([
    z.enum(["Automat", "Manuell"]),
    z.null()
  ]),
  sellerType: z.union([
    z.enum(["Företag", "Privat"]),
    z.null()
  ]),
})

//The enum is the expected schema response from the AI, and ICarSearchQueryType is the schema that we want to pass when setting data and creating blocket url.
export type ICarSearchQueryType = z.infer<typeof CarSearchResponseObject>
