const testCases: { input: string, expected: {} }[] = [
  {
    input: "Villa i Stockholm, max 10 miljoner SEK och 5 rum",
    expected: {
      maxListPrice: "10000000",
      minListPrice: "",
      rooms: "5",
      objectType: ["Villa"],
      location_names: ["Stockholm"],
      sort: "",
      ascending: "",
      maxRent: "",
      maxLivingArea: "",
      minLivingArea: "",
      minListSqmPrice: "",
      maxListSqmPrice: "",
      amenities: [""],
      floor: "",
      daysActive: "",
      showingStartRelative: "",
      minPlotArea: "",
      maxPlotArea: "",
      maxDistanceToWater: "",
      maxConstructionYear: "",
      minConstructionYear: "",
      showOnly: "",
      isNewConstruction: "",
      upcomingSale: ""
    }
  },
  {
    input: "Lägenhet i Göteborg för under 5 miljoner",
    expected: {
      maxListPrice: "5000000",
      minListPrice: "",
      rooms: "",
      objectType: ["Lägenhet"],
      location_names: ["Göteborg"],
      sort: "",
      ascending: "",
      maxRent: "",
      maxLivingArea: "",
      minLivingArea: "",
      minListSqmPrice: "",
      maxListSqmPrice: "",
      amenities: [""],
      floor: "",
      daysActive: "",
      showingStartRelative: "",
      minPlotArea: "",
      maxPlotArea: "",
      maxDistanceToWater: "",
      maxConstructionYear: "",
      minConstructionYear: "",
      showOnly: "",
      isNewConstruction: "",
      upcomingSale: ""
    }
  },
  {
    input: "Fritidshus nära sjön, maxpris 2 miljoner och minst 3 rum",
    expected: {
      maxListPrice: "2000000",
      minListPrice: "",
      rooms: "3",
      objectType: ["Fritidshus"],
      location_names: [],
      sort: "",
      ascending: "",
      maxRent: "",
      maxLivingArea: "",
      minLivingArea: "",
      minListSqmPrice: "",
      maxListSqmPrice: "",
      amenities: [""],
      floor: "",
      daysActive: "",
      showingStartRelative: "",
      minPlotArea: "",
      maxPlotArea: "",
      maxDistanceToWater: "100",
      maxConstructionYear: "",
      minConstructionYear: "",
      showOnly: "",
      isNewConstruction: "",
      upcomingSale: ""
    }
  },
  {
    input: "Tomt/Mark i Malmö, max 3 miljoner",
    expected: {
      maxListPrice: "3000000",
      minListPrice: "",
      rooms: "",
      objectType: ["Tomt/Mark"],
      location_names: ["Malmö"],
      sort: "",
      ascending: "",
      maxRent: "",
      maxLivingArea: "",
      minLivingArea: "",
      minListSqmPrice: "",
      maxListSqmPrice: "",
      amenities: [""],
      floor: "",
      daysActive: "",
      showingStartRelative: "",
      minPlotArea: "",
      maxPlotArea: "",
      maxDistanceToWater: "",
      maxConstructionYear: "",
      minConstructionYear: "",
      showOnly: "",
      isNewConstruction: "",
      upcomingSale: ""
    }
  },
  {
    input: "Radhus i Uppsala för minst 4 miljoner",
    expected: {
      maxListPrice: "",
      minListPrice: "4000000",
      rooms: "",
      objectType: ["Kedjehus-Parhus-Radhus"],
      location_names: ["Uppsala"],
      sort: "",
      ascending: "",
      maxRent: "",
      maxLivingArea: "",
      minLivingArea: "",
      minListSqmPrice: "",
      maxListSqmPrice: "",
      amenities: [""],
      floor: "",
      daysActive: "",
      showingStartRelative: "",
      minPlotArea: "",
      maxPlotArea: "",
      maxDistanceToWater: "",
      maxConstructionYear: "",
      minConstructionYear: "",
      showOnly: "",
      isNewConstruction: "",
      upcomingSale: ""
    }
  },
  {
    input: "Lägenhet med minst 2 rum i Linköping, max 1,5 miljoner",
    expected: {
      maxListPrice: "1500000",
      minListPrice: "",
      rooms: "2",
      objectType: ["Lägenhet"],
      location_names: ["Linköping"],
      sort: "",
      ascending: "",
      maxRent: "",
      maxLivingArea: "",
      minLivingArea: "",
      minListSqmPrice: "",
      maxListSqmPrice: "",
      amenities: [""],
      floor: "",
      daysActive: "",
      showingStartRelative: "",
      minPlotArea: "",
      maxPlotArea: "",
      maxDistanceToWater: "",
      maxConstructionYear: "",
      minConstructionYear: "",
      showOnly: "",
      isNewConstruction: "",
      upcomingSale: ""
    }
  },
  {
    input: "Villa i Danderyd för 8 miljoner och minst 4 rum",
    expected: {
      maxListPrice: "8000000",
      minListPrice: "",
      rooms: "4",
      objectType: ["Villa"],
      location_names: ["Danderyd"],
      sort: "",
      ascending: "",
      maxRent: "",
      maxLivingArea: "",
      minLivingArea: "",
      minListSqmPrice: "",
      maxListSqmPrice: "",
      amenities: [""],
      floor: "",
      daysActive: "",
      showingStartRelative: "",
      minPlotArea: "",
      maxPlotArea: "",
      maxDistanceToWater: "",
      maxConstructionYear: "",
      minConstructionYear: "",
      showOnly: "",
      isNewConstruction: "",
      upcomingSale: ""
    }
  },
  {
    input: "Fritidshus i Skåne med minst 1000 kvadratmeter tomt",
    expected: {
      maxListPrice: "",
      minListPrice: "",
      rooms: "",
      objectType: ["Fritidshus"],
      location_names: ["Skåne"],
      sort: "",
      ascending: "",
      maxRent: "",
      maxLivingArea: "",
      minLivingArea: "",
      minListSqmPrice: "",
      maxListSqmPrice: "",
      amenities: [""],
      floor: "",
      daysActive: "",
      showingStartRelative: "",
      minPlotArea: "1000",
      maxPlotArea: "",
      maxDistanceToWater: "",
      maxConstructionYear: "",
      minConstructionYear: "",
      showOnly: "",
      isNewConstruction: "",
      upcomingSale: ""
    }
  },
  {
    input: "Villa i centrala Stockholm för 20 miljoner",
    expected: {
      maxListPrice: "20000000",
      minListPrice: "",
      rooms: "",
      objectType: ["Villa"],
      location_names: ["centrala Stockholm"],
      sort: "",
      ascending: "",
      maxRent: "",
      maxLivingArea: "",
      minLivingArea: "",
      minListSqmPrice: "",
      maxListSqmPrice: "",
      amenities: [""],
      floor: "",
      daysActive: "",
      showingStartRelative: "",
      minPlotArea: "",
      maxPlotArea: "",
      maxDistanceToWater: "",
      maxConstructionYear: "",
      minConstructionYear: "",
      showOnly: "",
      isNewConstruction: "",
      upcomingSale: ""
    }
  },
  {
    input: "Lägenhet med balkong i Malmö under 3 miljoner",
    expected: {
      maxListPrice: "3000000",
      minListPrice: "",
      rooms: "",
      objectType: ["Lägenhet"],
      location_names: ["Malmö"],
      sort: "",
      ascending: "",
      maxRent: "",
      maxLivingArea: "",
      minLivingArea: "",
      minListSqmPrice: "",
      maxListSqmPrice: "",
      amenities: ["hasBalconyOrPatio"],
      floor: "",
      daysActive: "",
      showingStartRelative: "",
      minPlotArea: "",
      maxPlotArea: "",
      maxDistanceToWater: "",
      maxConstructionYear: "",
      minConstructionYear: "",
      showOnly: "",
      isNewConstruction: "",
      upcomingSale: ""
    }
  },
  {
    input: "Villa i Göteborg max 5 miljoner",
    expected: {
      maxListPrice: "5000000",
      minListPrice: "",
      rooms: "",
      objectType: ["Villa"],
      location_names: ["Göteborg"],
      sort: "",
      ascending: "",
      maxRent: "",
      maxLivingArea: "",
      minLivingArea: "",
      minListSqmPrice: "",
      maxListSqmPrice: "",
      amenities: [""],
      floor: "",
      daysActive: "",
      showingStartRelative: "",
      minPlotArea: "",
      maxPlotArea: "",
      maxDistanceToWater: "",
      maxConstructionYear: "",
      minConstructionYear: "",
      showOnly: "",
      isNewConstruction: "",
      upcomingSale: ""
    }
  },
  {
    input: "Radhus i Stockholm",
    expected: {
      maxListPrice: "",
      minListPrice: "",
      rooms: "",
      objectType: ["Kedjehus-Parhus-Radhus"],
      location_names: ["Stockholm"],
      sort: "",
      ascending: "",
      maxRent: "",
      maxLivingArea: "",
      minLivingArea: "",
      minListSqmPrice: "",
      maxListSqmPrice: "",
      amenities: [""],
      floor: "",
      daysActive: "",
      showingStartRelative: "",
      minPlotArea: "",
      maxPlotArea: "",
      maxDistanceToWater: "",
      maxConstructionYear: "",
      minConstructionYear: "",
      showOnly: "",
      isNewConstruction: "",
      upcomingSale: ""
    }
  },
  {
    input: "Hus under 1 miljon",
    expected: {
      maxListPrice: "1000000",
      minListPrice: "",
      rooms: "",
      objectType: [""],
      location_names: [],
      sort: "",
      ascending: "",
      maxRent: "",
      maxLivingArea: "",
      minLivingArea: "",
      minListSqmPrice: "",
      maxListSqmPrice: "",
      amenities: [""],
      floor: "",
      daysActive: "",
      showingStartRelative: "",
      minPlotArea: "",
      maxPlotArea: "",
      maxDistanceToWater: "",
      maxConstructionYear: "",
      minConstructionYear: "",
      showOnly: "",
      isNewConstruction: "",
      upcomingSale: ""
    }
  },
  {
    input: "Maxpris 2 miljoner, minst 3 rum",
    expected: {
      maxListPrice: "2000000",
      minListPrice: "",
      rooms: "3",
      objectType: [""],
      location_names: [],
      sort: "",
      ascending: "",
      maxRent: "",
      maxLivingArea: "",
      minLivingArea: "",
      minListSqmPrice: "",
      maxListSqmPrice: "",
      amenities: [""],
      floor: "",
      daysActive: "",
      showingStartRelative: "",
      minPlotArea: "",
      maxPlotArea: "",
      maxDistanceToWater: "",
      maxConstructionYear: "",
      minConstructionYear: "",
      showOnly: "",
      isNewConstruction: "",
      upcomingSale: ""
    }
  },
  {
    input: "Tomt i Skåne för under 1,5 miljoner",
    expected: {
      maxListPrice: "1500000",
      minListPrice: "",
      rooms: "",
      objectType: ["Tomt/Mark"],
      location_names: ["Skåne"],
      sort: "",
      ascending: "",
      maxRent: "",
      maxLivingArea: "",
      minLivingArea: "",
      minListSqmPrice: "",
      maxListSqmPrice: "",
      amenities: [""],
      floor: "",
      daysActive: "",
      showingStartRelative: "",
      minPlotArea: "",
      maxPlotArea: "",
      maxDistanceToWater: "",
      maxConstructionYear: "",
      minConstructionYear: "",
      showOnly: "",
      isNewConstruction: "",
      upcomingSale: ""
    }
  },
  {
    input: "Lägenhet med balkong och öppen spis i Stockholm, max 7 miljoner",
    expected: {
      maxListPrice: "7000000",
      minListPrice: "",
      rooms: "",
      objectType: ["Lägenhet"],
      location_names: ["Stockholm"],
      sort: "",
      ascending: "",
      maxRent: "",
      maxLivingArea: "",
      minLivingArea: "",
      minListSqmPrice: "",
      maxListSqmPrice: "",
      amenities: ["hasBalconyOrPatio", "hasFireplace"],
      floor: "",
      daysActive: "",
      showingStartRelative: "",
      minPlotArea: "",
      maxPlotArea: "",
      maxDistanceToWater: "",
      maxConstructionYear: "",
      minConstructionYear: "",
      showOnly: "",
      isNewConstruction: "",
      upcomingSale: ""
    }
  },
  {
    input: "Lägenhet i Malmö max 4,5 miljoner, minst 3 rum och 90 kvadratmeter",
    expected: {
      maxListPrice: "4500000",
      minListPrice: "",
      rooms: "3",
      objectType: ["Lägenhet"],
      location_names: ["Malmö"],
      sort: "",
      ascending: "",
      maxRent: "",
      maxLivingArea: "",
      minLivingArea: "90",
      minListSqmPrice: "",
      maxListSqmPrice: "",
      amenities: [""],
      floor: "",
      daysActive: "",
      showingStartRelative: "",
      minPlotArea: "",
      maxPlotArea: "",
      maxDistanceToWater: "",
      maxConstructionYear: "",
      minConstructionYear: "",
      showOnly: "",
      isNewConstruction: "",
      upcomingSale: ""
    }
  },
  {
    input: "Villa på landet, max 2 miljoner, byggt efter 1980",
    expected: {
      maxListPrice: "2000000",
      minListPrice: "",
      rooms: "",
      objectType: ["Villa"],
      location_names: ["landet"],
      sort: "",
      ascending: "",
      maxRent: "",
      maxLivingArea: "",
      minLivingArea: "",
      minListSqmPrice: "",
      maxListSqmPrice: "",
      amenities: [""],
      floor: "",
      daysActive: "",
      showingStartRelative: "",
      minPlotArea: "",
      maxPlotArea: "",
      maxDistanceToWater: "",
      maxConstructionYear: "",
      minConstructionYear: "1980",
      showOnly: "",
      isNewConstruction: "",
      upcomingSale: ""
    }
  },
  {
    input: "Lägenhet i Stockholm för 15 miljoner, toppvåning",
    expected: {
      maxListPrice: "15000000",
      minListPrice: "",
      rooms: "",
      objectType: ["Lägenhet"],
      location_names: ["Stockholm"],
      sort: "",
      ascending: "",
      maxRent: "",
      maxLivingArea: "",
      minLivingArea: "",
      minListSqmPrice: "",
      maxListSqmPrice: "",
      amenities: [""],
      floor: "topFloor",
      daysActive: "",
      showingStartRelative: "",
      minPlotArea: "",
      maxPlotArea: "",
      maxDistanceToWater: "",
      maxConstructionYear: "",
      minConstructionYear: "",
      showOnly: "",
      isNewConstruction: "",
      upcomingSale: ""
    }
  },
  {
    input: "Villa nära havet i Skåne, maxpris 12 miljoner",
    expected: {
      maxListPrice: "12000000",
      minListPrice: "",
      rooms: "",
      objectType: ["Villa"],
      location_names: ["Skåne"],
      sort: "",
      ascending: "",
      maxRent: "",
      maxLivingArea: "",
      minLivingArea: "",
      minListSqmPrice: "",
      maxListSqmPrice: "",
      amenities: [""],
      floor: "",
      daysActive: "",
      showingStartRelative: "",
      minPlotArea: "",
      maxPlotArea: "",
      maxDistanceToWater: "1000",
      maxConstructionYear: "",
      minConstructionYear: "",
      showOnly: "",
      isNewConstruction: "",
      upcomingSale: ""
    }
  },
  {
    input: "Fritidshus max 3 miljoner med minst 500 kvadratmeter tomt",
    expected: {
      maxListPrice: "3000000",
      minListPrice: "",
      rooms: "",
      objectType: ["Fritidshus"],
      location_names: [],
      sort: "",
      ascending: "",
      maxRent: "",
      maxLivingArea: "",
      minLivingArea: "",
      minListSqmPrice: "",
      maxListSqmPrice: "",
      amenities: [""],
      floor: "",
      daysActive: "",
      showingStartRelative: "",
      minPlotArea: "500",
      maxPlotArea: "",
      maxDistanceToWater: "",
      maxConstructionYear: "",
      minConstructionYear: "",
      showOnly: "",
      isNewConstruction: "",
      upcomingSale: ""
    }
  },
  {
    input: "Villa eller lägenhet i Malmö för runt 5 miljoner",
    expected: {
      maxListPrice: "5000000", // Interpreting "runt 5 miljoner" as 5M
      minListPrice: "",
      rooms: "",
      objectType: ["Villa", "Lägenhet"], // Ambiguity: Could be either Villa or Lägenhet
      location_names: ["Malmö"],
      sort: "",
      ascending: "",
      maxRent: "",
      maxLivingArea: "",
      minLivingArea: "",
      minListSqmPrice: "",
      maxListSqmPrice: "",
      amenities: [""],
      floor: "",
      daysActive: "",
      showingStartRelative: "",
      minPlotArea: "",
      maxPlotArea: "",
      maxDistanceToWater: "",
      maxConstructionYear: "",
      minConstructionYear: "",
      showOnly: "",
      isNewConstruction: "",
      upcomingSale: ""
    }
  },
  {
    input: "En bostad i Sverige under 10 miljoner",
    expected: {
      maxListPrice: "10000000",
      minListPrice: "",
      rooms: "",
      objectType: [""], // Ambiguous: No specific type mentioned
      location_names: ["Sverige"], // Very broad location
      sort: "",
      ascending: "",
      maxRent: "",
      maxLivingArea: "",
      minLivingArea: "",
      minListSqmPrice: "",
      maxListSqmPrice: "",
      amenities: [""],
      floor: "",
      daysActive: "",
      showingStartRelative: "",
      minPlotArea: "",
      maxPlotArea: "",
      maxDistanceToWater: "",
      maxConstructionYear: "",
      minConstructionYear: "",
      showOnly: "",
      isNewConstruction: "",
      upcomingSale: ""
    }
  },
  {
    input: "Lägenhet i Stockholm eller Göteborg, gärna nära centrum",
    expected: {
      maxListPrice: "",
      minListPrice: "",
      rooms: "",
      objectType: ["Lägenhet"],
      location_names: ["Stockholm", "Göteborg"], // Multiple locations
      sort: "",
      ascending: "",
      maxRent: "",
      maxLivingArea: "",
      minLivingArea: "",
      minListSqmPrice: "",
      maxListSqmPrice: "",
      amenities: [""], // No clear amenity, "nära centrum" is ambiguous
      floor: "",
      daysActive: "",
      showingStartRelative: "",
      minPlotArea: "",
      maxPlotArea: "",
      maxDistanceToWater: "",
      maxConstructionYear: "",
      minConstructionYear: "",
      showOnly: "",
      isNewConstruction: "",
      upcomingSale: ""
    }
  },
  {
    input: "Hus i någon stor stad i Skåne, max 3 miljoner",
    expected: {
      maxListPrice: "3000000",
      minListPrice: "",
      rooms: "",
      objectType: ["Villa", "Kedjehus-Parhus-Radhus", "Fritidshus", "Gård"], // Ambiguous type: "Hus" can refer to different types of houses
      location_names: ["Skåne"], // "Någon stor stad" is unclear
      sort: "",
      ascending: "",
      maxRent: "",
      maxLivingArea: "",
      minLivingArea: "",
      minListSqmPrice: "",
      maxListSqmPrice: "",
      amenities: [""],
      floor: "",
      daysActive: "",
      showingStartRelative: "",
      minPlotArea: "",
      maxPlotArea: "",
      maxDistanceToWater: "",
      maxConstructionYear: "",
      minConstructionYear: "",
      showOnly: "",
      isNewConstruction: "",
      upcomingSale: ""
    }
  },
  {
    input: "En bostad nära havet, högst 4 rum och minst 100 kvadratmeter",
    expected: {
      maxListPrice: "",
      minListPrice: "",
      rooms: "4",
      objectType: [""], // Ambiguous: "Bostad" could refer to any type
      location_names: [], // "Nära havet" isn't a concrete location
      sort: "",
      ascending: "",
      maxRent: "",
      maxLivingArea: "",
      minLivingArea: "100",
      minListSqmPrice: "",
      maxListSqmPrice: "",
      amenities: [""],
      floor: "",
      daysActive: "",
      showingStartRelative: "",
      minPlotArea: "",
      maxPlotArea: "",
      maxDistanceToWater: "1000", // "Nära havet" interpreted as max 1000 meters from water
      maxConstructionYear: "",
      minConstructionYear: "",
      showOnly: "",
      isNewConstruction: "",
      upcomingSale: ""
    }
  },
  {
    input: "Tomt någonstans i södra Sverige för 2 miljoner",
    expected: {
      maxListPrice: "2000000",
      minListPrice: "",
      rooms: "",
      objectType: ["Tomt/Mark"],
      location_names: ["södra Sverige"], // Ambiguous: "Någonstans" and "södra Sverige" are vague
      sort: "",
      ascending: "",
      maxRent: "",
      maxLivingArea: "",
      minLivingArea: "",
      minListSqmPrice: "",
      maxListSqmPrice: "",
      amenities: [""],
      floor: "",
      daysActive: "",
      showingStartRelative: "",
      minPlotArea: "",
      maxPlotArea: "",
      maxDistanceToWater: "",
      maxConstructionYear: "",
      minConstructionYear: "",
      showOnly: "",
      isNewConstruction: "",
      upcomingSale: ""
    }
  },
  {
    input: "Nybyggd villa i närheten av Stockholm, max 12 miljoner",
    expected: {
      maxListPrice: "12000000",
      minListPrice: "",
      rooms: "",
      objectType: ["Villa"],
      location_names: ["närheten av Stockholm"], // Ambiguous: "I närheten av" is vague
      sort: "",
      ascending: "",
      maxRent: "",
      maxLivingArea: "",
      minLivingArea: "",
      minListSqmPrice: "",
      maxListSqmPrice: "",
      amenities: [""],
      floor: "",
      daysActive: "",
      showingStartRelative: "",
      minPlotArea: "",
      maxPlotArea: "",
      maxDistanceToWater: "",
      maxConstructionYear: "",
      minConstructionYear: "",
      showOnly: "",
      isNewConstruction: "1", // Explicit "nybyggd" (new construction)
      upcomingSale: ""
    }
  },
];
